# Generated by Django 5.1.4 on 2024-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=15)),
                ('Lname', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('contacts', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=255)),
            ],
        ),
    ]
