# Generated by Django 5.1.4 on 2024-12-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('contacts', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('job_title', models.CharField(choices=[('Gardener', 'Gardener'), ('Maintenance Technician', 'Maintenance Technician'), ('Horticulturist', 'Horticulturist')], max_length=100)),
                ('hire_date', models.DateField()),
                ('employment_type', models.CharField(max_length=50)),
            ],
        ),
    ]
