# Generated by Django 5.1.4 on 2024-12-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('employees', models.ManyToManyField(to='app.employee')),
            ],
        ),
    ]
