# Generated by Django 5.1.4 on 2024-12-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Gardening', 'Gardening'), ('Consultation', 'Consultation')], max_length=50)),
                ('service_description', models.TextField()),
                ('service_duration', models.DurationField()),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
